import { runBasicTypesExamples } from "./src/topics/01-basic-types.js";
import { runStructuralTypingExamples } from "./src/topics/02-structural-typing.js";
import { runUnionsAndIntersectionsExamples } from "./src/topics/03-unions-intersections.js";
import { runSpecialTypesExamples } from "./src/topics/04-special-types.js";
import { runCompoundAndLiteralExamples } from "./src/topics/05-compound-literals.js";
import { runGenericExamples } from "./src/topics/06-generics.js";
import { runNarrowingExamples } from "./src/topics/07-narrowing.js";
import { runTypeToolsExamples } from "./src/topics/08-type-tools.js";
import { runEnumExamples } from "./src/topics/09-enums.js";
runBasicTypesExamples();
runStructuralTypingExamples();
runUnionsAndIntersectionsExamples();
runSpecialTypesExamples();
runCompoundAndLiteralExamples();
runGenericExamples();
runNarrowingExamples();
runTypeToolsExamples();
runEnumExamples();
